### ISSUE TITLE
Doesn't work as expected on ShadowNAND

### ISSUE THREAD

**Issue by robflop** [Wolfvak/BootAnim9#12]
Bootanim9 doesn't seem to work seamlessly if you're using ShadowNAND -- it blackscreens because of screeninit. 

It only works if you manually activate screeninit on boot (DPAD_LEFT), but I was told that Bootanim9 should activate screeninit on its own without any user input.

Edit: Apparently it does not work properly on A9LHv3 either.

**Comment by Wolfvak** [comment]
RTFM

 "Robin B." <notifications@github.com> wrote:



Bootanim9 doesn't seem to work seamlessly if you're using ShadowNAND -- it blackscreen because of screeninit.

It only works if you manually activate screeninit (DPAD_LEFT), but I was told that Bootanim9 should activate screeninit on its own without any user input.

-
